apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-service-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    component: stolon-proxy
    stolon-cluster: kube-stolon
